### ISSUE TITLE
Bugs with bugs

### ISSUE THREAD

**Issue by afruitlesshippo** [FluffierThanThou/FluffyBreakdowns#13]
Shortly after getting an infestation, I get this message on the bug hives. They disappear less than a day after this message, usually before they can reproduce.

Image of issue; [https://gyazo.com/d703ff7eb9d8671402261186f912f3ac](url)
Save file; [https://uploadfiles.io/1c1qb](url)
Mod config; [https://ufile.io/azg0v](url)

**Comment by FluffierThanThou** [comment]
that is so weird.... 

I'll look into it!

**Comment by FluffierThanThou** [comment]
turns out this isn't FluffyBreakdowns at all, it's a vanilla job related to maintaining hives, and the error is a more general bug with animals and reservations. 

https://ludeon.com/forums/index.php?topic=32671.0
