### ISSUE TITLE
Error with RT Fuse upon loading savegame

### ISSUE THREAD

**Issue by Mythos** [FluffierThanThou/FluffyBreakdowns#14]
Hey there,

when I'm loading the game, I'm getting these exceptions (2 same ones, just different IDs):

```
Exception in SetupToils (pawn=Bender, job=FluffyBreakdowns_Maintenance A=Thing_Building_RTMakeshiftFuse453887): System.NullReferenceException: Object reference not set to an instance of an object
  at Fluffy_Breakdowns.MapComponent_Durability.ForMap (Verse.Map map) [0x00000] in <filename unknown>:0 
  at Fluffy_Breakdowns.JobDriver_Maintenance.get_durability () [0x00000] in <filename unknown>:0 
  at Fluffy_Breakdowns.JobDriver_Maintenance+<MakeNewToils>d__2.MoveNext () [0x00000] in <filename unknown>:0 
  at Verse.AI.JobDriver.SetupToils () [0x00000] in <filename unknown>:0  lastJobGiver=RimWorld.JobGiver_Work, curJob.def=FluffyBreakdowns_Maintenance, curDriver=Fluffy_Breakdowns.JobDriver_Maintenance
Verse.Log:Error(String)
Verse.AI.Pawn_JobTracker:StartErrorRecoverJob(String)
Verse.AI.JobDriver:SetupToils()
Verse.AI.JobDriver:ExposeData()
Verse.PostLoadIniter:DoAllPostLoadInits()
Verse.ScribeLoader:FinalizeLoading()
Verse.Game:LoadGame()
Verse.SavedGameLoader:LoadGameFromSaveFile(String)
Verse.Root_Play:<Start>m__84F()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__84C()
```

**Comment by FluffierThanThou** [comment]
Hmm, this might be a tougher one =/

**Comment by FluffierThanThou** [comment]
would you be able/willing to test a few versions manually? This looks like a highly context-dependent issue. I have a fairly good idea of whats going on, but I can't be sure without testing.

**Comment by Mythos** [comment]
I will test of course. ;-)
Unfortunately I've added another one in WorkTab :P

**Comment by FluffierThanThou** [comment]
hah, no worries :) I'm putting a pre-release up on git in a few secs, please try and load that savegame again.

**Comment by FluffierThanThou** [comment]
and then github crashed... trying again!

**Comment by Mythos** [comment]
Yep they are having some problems atm. :D

**Comment by FluffierThanThou** [comment]
aight, try installing v0.17.1.2. It's only on github though, don't wanna disturb steam with a release that may or may not work.

**Comment by Mythos** [comment]
No error anymore! ;-)

**Comment by FluffierThanThou** [comment]
awesome! I'll make it a proper release then.

**Comment by Mythos** [comment]
Hey there,

unfortunately I got this exception again when loading a map:
```
Exception in SetupToils (pawn=Moreno, job=FluffyBreakdowns_Maintenance A=Thing_Cooler645632): System.NullReferenceException: Object reference not set to an instance of an object
  at Fluffy_Breakdowns.MapComponent_Durability.ForMap (Verse.Map map) [0x00000] in <filename unknown>:0 
  at Fluffy_Breakdowns.JobDriver_Maintenance.get_Durability () [0x00000] in <filename unknown>:0 
  at Fluffy_Breakdowns.JobDriver_Maintenance+<MakeNewToils>d__2.MoveNext () [0x00000] in <filename unknown>:0 
  at Verse.AI.JobDriver.SetupToils () [0x00000] in <filename unknown>:0  lastJobGiver=RimWorld.JobGiver_Work, curJob.def=FluffyBreakdowns_Maintenance, curDriver=Fluffy_Breakdowns.JobDriver_Maintenance
Verse.Log:Error(String)
Verse.AI.Pawn_JobTracker:StartErrorRecoverJob(String)
Verse.AI.JobDriver:SetupToils()
Verse.AI.JobDriver:ExposeData()
Verse.PostLoadIniter:DoAllPostLoadInits()
Verse.ScribeLoader:FinalizeLoading()
Verse.Game:LoadGame()
Verse.SavedGameLoader:LoadGameFromSaveFile(String)
Verse.Root_Play:<Start>m__84F()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__84C()
```

Steam should have downloaded the latest version. Unfortunately I can't see which version I have. (Assembly has 1.0.0.0 and About.xml doesn't have a version except the target version 0.17.1557)

**Comment by Mythos** [comment]
The "Thing_Cooler" might probably be from "Redist Heat".

**Comment by FluffierThanThou** [comment]
the actual thing is probably irrelevant. I'm going to re-compile and upload the same latest version again, I've now added version information to the about.xml. The assembly also should have had version information, so I'm trying to figure out why it apparently doesn't.

**Comment by FluffierThanThou** [comment]
ok I've fixed my build script, there were some spaces in the assemblyInfo file so it didn't properly recognize and update the version number (using regex for that). 

Also double checked my previous fix, and it does appear I may have misinterpreted what the actual problem was. Let me know if the latest version (v0.17.1.6 now) still has issues.

**Comment by Mythos** [comment]
Didn't happen to me anymore! :)
