### ISSUE TITLE
ru language

### ISSUE THREAD

**Issue by Well-sp** [FluffierThanThou/FluffyBreakdowns#16]
https://drive.google.com/file/d/0B2YbDFbz4u9nd3V0VC0tVjduMU0/view?usp=sharing

May be of interest (Colony Manager)- https://drive.google.com/file/d/0B2YbDFbz4u9nQmFkazBFRVYyYnc/view?usp=sharing

**Comment by FluffierThanThou** [comment]
thanks, I'll look at them tonight
