### ISSUE TITLE
[Suggestion] Maintenance Drain

### ISSUE THREAD

**Issue by VasVadum** [FluffierThanThou/FluffyBreakdowns#19]
Along with something mentioned earlier with a slider that adds difficulty or whatever, I thought I'd pitch in an option that increases maintenance drain on things with more than 1 component, multiplied on a per component basis.

Personally I think they all drain too fast, but that can be fixed by setting the main drain speed to 2 components.

1 component | 0.50x drain speed
2 components | 1.00x drain speed
3 components | 1.18x drain speed
4 components | 1.38x drain speed
5 components | 1.63x drain speed
6 components | 1.92x drain speed
7 components | 2.25x drain speed
8 components | 2.65x drain speed
9 components | 3.12x drain speed
10 components | 3.67x drain speed
11 components | 4.32x drain speed
12 components | 5.08x drain speed
13 components | 5.98x drain speed
14 components | 7.03x drain speed
15 components | 8.27x drain speed

Used a spreadsheet to get the math done for me.  This is just an example however.

**Comment by FluffierThanThou** [comment]
implemented 

rate = sqrt( numcomponents / 2 )
