### ISSUE TITLE
Your name is literally all over this

### ISSUE THREAD

**Issue by ChevalierXLIV** [FluffierThanThou/FluffyBreakdowns#25]
https://discord.gg/E52RQ9

everything requested in your bug report guide is in the discord channel above, for reference, this is the issue
![image](https://user-images.githubusercontent.com/44930420/48305197-f7c30200-e4eb-11e8-984d-b5940ed48204.png)
and as you imagine, it makes playing the game quite difficult ^_^

**Comment by FluffierThanThou** [comment]
hehe, no worries 👍  It's not often I get to see bugs this funny :p
