### ISSUE TITLE
Biotech mechanoids are stuck standing when something needs maintenance

### ISSUE THREAD

**Issue by EmeraldSeas** [FluffierThanThou/FluffyBreakdowns#35]
**Describe the bug**  

Mechanoids are stuck in a "Standing" behavior when something needs maintenance.
**Expected behavior**  

For mechanoids to properly maintain buildings.
**Steps to reproduce**  

1. Build something that needs maintenance.
2. Get a mechanitor and constructoid.
3. Watch as constructoids sit still until a human maintains somethings that needs maintenance.

**Other mods**  

**Output log**  

I am not running HugsLib.
**Save game**  

[New Arrivals14.zip](https://github.com/fluffy-mods/FluffyBreakdowns/files/9841041/New.Arrivals14.zip)
**Screenshots**  

**Environment**  
 - OS: Windows 10
 - 32/64 bits: 64
**Game**
 - Steam, 1.4.3523

**Comment by Allanva** [comment]
Hi! I ran into this bug as well, seems to be an interaction between the Biotech mechanoids and fluffy breakdowns, this is the error I see on the console whenever the bot just stands there:

Exception in JobDriver tick for pawn Mech_Constructoid75846 driver=JobDriver_Maintenance (toilIndex=1) driver.job=(FluffyBreakdowns_Maintenance (Job_1311656) A=Thing_VFE_TableDrugLabElectric132571)
System.NullReferenceException: Object reference not set to an instance of an object
  at Fluffy_Breakdowns.JobDriver_Maintenance+<>c__DisplayClass3_0.<MakeNewToils>b__0 () [0x00036] in <a1c7149df60a40afb73fef16e2ea1bb5>:0 
  at Verse.AI.JobDriver.DriverTick () [0x00163] in <a00f98f6defb48d0a26adc267eeace6e>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.AI.JobUtility:TryStartErrorRecoverJob (Verse.Pawn,string,System.Exception,Verse.AI.JobDriver)
Verse.AI.JobDriver:DriverTick ()
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch3 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()

**Comment by Hogedal** [comment]
I am also getting this same error when mechanoids try to do maintainance.

**Comment by SuiNakigai** [comment]
I am having the exact same issue. Fluffy Breakdown maintenance collides with Biotech mechanoids trying to maintain my doors. Haven't seen it try to repair other objects yet.

Same logs as above.

**Comment by VernaSaurus** [comment]
fixed with #36 which hasn't been applied yet

**Comment by Karel-Kroeze** [comment]
#36 was merged, new release has been pushed - this should be fixed.
