### ISSUE TITLE
Unpowered structures lose maintenance rating

### ISSUE THREAD

**Issue by cwc** [FluffierThanThou/FluffyBreakdowns#8]
I've got heaters and coolers that are powered off, but their maintenance level is still decreasing. I see there's a check for powered status and it looks pretty straightforward, but it doesn't seem to be having any effect. Maybe there's a bug somewhere?

**Comment by cwc** [comment]
After reading more thoroughly, I see that structures that aren't in use lose their maintenance level at 1/3rd of the normal rate. Perhaps this amount should be configurable in the mod settings? I personally find it a bit overwhelming to have to maintain all of my coolers, heaters, hydro bays etc. that are turned off when not in use.

**Comment by FluffierThanThou** [comment]
heya, I can tweak the percentages a bit. I don't really want to expose too many of these settings - it feels a bit like cheating.

Also, keep in mind that in vanilla all of these would have a chance of breaking down regardless of being used or not.

**Comment by cwc** [comment]
Yeah, the random breakdowns in vanilla have always annoyed me, because unlike with other random events, there's not really any counter play. E.g. you can build defenses against raids, make redundant power lines & disconnect backup batteries to handle short circuits, stockpile medicine to counter diseases, etc. I really like your maintenance idea, because the player has the ability to mitigate the disaster chance.

IMO, it's worth it for a mod like this, which changes the game's balance, to expose some of those balance values for tweaking by the user. If you feel it's too easy/cheaty to set unused maintenance decay to 0, you can use a higher value. There is something to be said for exposing *too* many settings and overwhelming the user, of course.
